src/main/java/it/unitn/disi/wp/cup/bean/config/AuthConfigBean.java
package it.unitn.disi.wp.cup.bean.config;

import it.unitn.disi.wp.cup.config.AuthConfig;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * Permits the access to web pages of the Auth Configuration
 * The Configuration is filtered leaving only NON sensible information
 *
 * @author Carlo Corradini
 * @see AuthConfig
 */
@Named("auth")
@ApplicationScoped
public final class AuthConfigBean implements Serializable {
    private static final long serialVersionUID = 3487302701712952518L;

    /**
     * @see AuthConfig#getPasswordMinLength()
     */
    public int getPasswordMinLength() {
        return AuthConfig.getPasswordMinLength();
    }

    /**
     * @see AuthConfig#getPasswordMaxLength()
     */
    public int getPasswordMaxLength() {
        return AuthConfig.getPasswordMaxLength();
    }
}

src/main/java/it/unitn/disi/wp/cup/persistence/entity/HealthService.java
package it.unitn.disi.wp.cup.persistence.entity;

import it.unitn.disi.wp.cup.config.AppConfig;

/**
 * Entity Health Service
 *
 * @author Carlo Corradini
 */
public class HealthService {
    private Long id;
    private String password;
    private String email;
    private String crest;
    private Province province;

    @Override
    public boolean equals(Object obj) {
        HealthService healthService;
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        healthService = (HealthService) obj;
        return id.equals(healthService.id);
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        return prime + ((id == null) ? 0 : id.hashCode());
    }

    /**
     * Return the id of the Health Service
     *
     * @return Health Service id
     */
    public Long getId() {
        return id;
    }

    /**
     * Set the id of the Health Service
     *
     * @param id Health Service id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Return the password of the Health Service
     *
     * @return Health Service password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the password of the Health Service
     *
     * @param password Health Service password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Return the email of the Health service
     *
     * @return Health Service email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Set the email of the Health Service
     *
     * @param email Health Service email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Return the crest of the Health Service
     *
     * @return Health Service crest
     */
    public String getCrest() {
        return crest;
    }

    /**
     * Set the crest of the Health Service
     *
     * @param crest Health Service crest
     */
    public void setCrest(String crest) {
        this.crest = crest;
    }

    /**
     * Return the name of the {@code crest} for resource usage
     *
     * @return The crest as Resource
     */
    public String getCrestAsResource() {
        return AppConfig.getConfigImagePath() + getCrestAsImage();
    }

    /**
     * Return the name of the {@code crest} for Server Side usage
     *
     * @return The crest as Image
     */
    public String getCrestAsImage() {
        return AppConfig.getConfigCrestPath() + "/" + crest + AppConfig.getConfigCrestExtension();
    }

    /**
     * Return the {@link Province Province} of the Health Service
     *
     * @return Health Service {@link Province Province}
     */
    public Province getProvince() {
        return province;
    }

    /**
     * Set the {@link Province Province} of the Health Service
     *
     * @param province Health Service {@link Province Province}
     */
    public void setProvince(Province province) {
        this.province = province;
    }
}

src/main/java/it/unitn/disi/wp/cup/persistence/entity/Province.java
package it.unitn.disi.wp.cup.persistence.entity;

import it.unitn.disi.wp.cup.util.StringUtil;

/**
 * Entity Province
 *
 * @author Carlo Corradini
 */
public class Province {
    private Long id;
    private String nameLong;
    private String nameShort;
    private Region region;

    @Override
    public boolean equals(Object obj) {
        Province province;
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        province = (Province) obj;
        return id.equals(province.id);
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        return prime + ((id == null) ? 0 : id.hashCode());
    }

    /**
     * Return the id of the Province
     *
     * @return Province id
     */
    public Long getId() {
        return id;
    }

    /**
     * Set the Province id
     *
     * @param id Province id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Return the name long of the Province
     *
     * @return Province name long
     */
    public String getNameLong() {
        return nameLong;
    }

    /**
     * Return the name long of the Province capitalized
     *
     * @return Province name long capitalized
     */
    public String getNameLongCapitalized() {
        return StringUtil.capitalize(nameLong);
    }

    /**
     * Set the Province name long
     *
     * @param nameLong Province name long
     */
    public void setNameLong(String nameLong) {
        this.nameLong = nameLong;
    }

    /**
     * Return the name short of the Province
     * The name short is always in Upper Case
     *
     * @return Province name short
     */
    public String getNameShort() {
        return nameShort.toUpperCase();
    }

    /**
     * Set the Province name short
     *
     * @param nameShort Province name short
     */
    public void setNameShort(String nameShort) {
        this.nameShort = nameShort;
    }

    /**
     * Return the Region of the Province
     *
     * @return Province Region
     */
    public Region getRegion() {
        return region;
    }

    /**
     * Set the Province region
     *
     * @param region Province region
     */
    public void setRegion(Region region) {
        this.region = region;
    }
}

src/main/java/it/unitn/disi/wp/cup/service/model/health_service/AssignPrescriptionExamModel.java
package it.unitn.disi.wp.cup.service.model.health_service;

import it.unitn.disi.wp.cup.config.PrescriptionConfig;
import it.unitn.disi.wp.cup.service.model.Model;
import it.unitn.disi.wp.cup.service.model.obj.DateTimeModel;
import it.unitn.disi.wp.cup.persistence.entity.PrescriptionExam;
import it.unitn.disi.wp.cup.persistence.entity.Exam;
import it.unitn.disi.wp.cup.persistence.entity.DoctorSpecialist;
import it.unitn.disi.wp.cup.persistence.entity.HealthService;

/**
 * Assign {@link PrescriptionExam} Model for assigning a {@link PrescriptionExam} to an executor
 *
 * @author Carlo Corradini
 */
public class AssignPrescriptionExamModel implements Model {
    private long prescriptionId;
    private long executorId;
    private DateTimeModel dateTime;

    AssignPrescriptionExamModel() {
        prescriptionId = 0L;
        executorId = 0L;
        dateTime = null;
    }

    /**
     * Set the {@link PrescriptionExam} id
     *
     * @param prescriptionId The {@link PrescriptionExam} id
     */
    public void setPrescriptionId(long prescriptionId) {
        this.prescriptionId = prescriptionId;
    }

    /**
     * Return the {@link PrescriptionExam} id
     *
     * @return The {@link PrescriptionExam} id
     */
    public long getPrescriptionId() {
        return prescriptionId;
    }

    /**
     * Set the Executor id
     * If the {@link Exam} is supported this must be a valid {@link DoctorSpecialist} id
     * else if it's not supported this must be a valid {@link HealthService} id equals to the current authenticated
     * {@link HealthService Health Service}
     *
     * @param executorId The Executor id
     */
    public void setExecutorId(long executorId) {
        this.executorId = executorId;
    }

    /**
     * Return the executor id
     *
     * @return The Executor id
     */
    public long getExecutorId() {
        return executorId;
    }

    /**
     * Set the {@link DateTimeModel Date Time Model} of the {@link PrescriptionExam Prescription Exam}
     *
     * @param dateTime The {@link DateTimeModel Date Time Model} of the {@link PrescriptionExam Prescription Exam}
     */
    public void setDateTime(DateTimeModel dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * Return the {@link DateTimeModel Date Time Model} of the {@link PrescriptionExam Prescription Exam}
     *
     * @return The {@link DateTimeModel Date Time Model} of the {@link PrescriptionExam Prescription Exam}
     */
    public DateTimeModel getDateTime() {
        return dateTime;
    }

    @Override
    public boolean isValid() {
        return prescriptionId != 0L && executorId != 0L
                && dateTime != null && dateTime.isValid()
                && dateTime.toLocalDateTime().getHour() >= PrescriptionConfig.getExamMinTime()
                && dateTime.toLocalDateTime().getHour() <= PrescriptionConfig.getExamMaxTime();
    }
}

src/main/java/it/unitn/disi/wp/cup/service/model/health_service/AssignPrescriptionMedicineModel.java
package it.unitn.disi.wp.cup.service.model.health_service;

import it.unitn.disi.wp.cup.service.model.Model;
import it.unitn.disi.wp.cup.persistence.entity.Person;
import it.unitn.disi.wp.cup.persistence.entity.PrescriptionMedicine;

/**
 * Assign {@link PrescriptionMedicine} Model for assigning a {@link PrescriptionMedicine} to a {@link Person Person}
 *
 * @author Carlo Corradini
 */
public class AssignPrescriptionMedicineModel implements Model {
    private long prescriptionId;
    private boolean paid;

    AssignPrescriptionMedicineModel() {
        prescriptionId = 0L;
        paid = false;
    }

    /**
     * Set the {@link PrescriptionMedicine} id
     *
     * @param prescriptionId The {@link PrescriptionMedicine} id
     */
    public void setPrescriptionId(long prescriptionId) {
        this.prescriptionId = prescriptionId;
    }

    /**
     * Return the {@link PrescriptionMedicine} id
     *
     * @return The {@link PrescriptionMedicine} id
     */
    public long getPrescriptionId() {
        return prescriptionId;
    }

    /**
     * Return if the {@link PrescriptionMedicine Prescription Medicine} has been paid
     *
     * @return True if paid, false otherwise
     */
    public boolean isPaid() {
        return paid;
    }

    /**
     * Set if the {@link PrescriptionMedicine Prescription Medicine} has been paid
     *
     * @param paid True if paid, false otherwise
     */
    public void setPaid(boolean paid) {
        this.paid = paid;
    }

    @Override
    public boolean isValid() {
        return prescriptionId != 0L && paid;
    }
}

src/main/java/it/unitn/disi/wp/cup/service/model/health_service/CredentialsModel.java
package it.unitn.disi.wp.cup.service.model.health_service;

import it.unitn.disi.wp.cup.config.AuthConfig;
import it.unitn.disi.wp.cup.persistence.entity.HealthService;
import it.unitn.disi.wp.cup.service.model.Model;

/**
 * Credentials Model for authenticating the {@link HealthService Health Service}
 *
 * @author Carlo Corradini
 */
public class CredentialsModel implements Model {
    private long id;
    private String password;
    private boolean remember;

    CredentialsModel() {
        id = 0L;
        password = "";
        remember = false;
    }

    /**
     * Return the id of the {@link HealthService Health Service}
     *
     * @return id of the {@link HealthService Health Service}
     */
    public long getId() {
        return id;
    }

    /**
     * Set the id of the {@link HealthService Health Service}
     *
     * @param id The id of the {@link HealthService Health Service}
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Return the password of the {@link HealthService Health Service}
     *
     * @return The password of the {@link HealthService Health Service}
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the password of the {@link HealthService Health Service}
     *
     * @param password The password of the {@link HealthService Health Service}
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Return if the authenticated {@link HealthService Health Service} session must be remembered or not
     *
     * @return True if remember, false otherwise
     */
    public boolean isRemember() {
        return remember;
    }

    /**
     * Set if the authenticated {@link HealthService Health Service} session must be remembered or not
     *
     * @param remember True if remember, false otherwise
     */
    public void setRemember(boolean remember) {
        this.remember = remember;
    }

    @Override
    public boolean isValid() {
        return id != 0L
                && !password.isEmpty()
                && password.length() >= AuthConfig.getPasswordMinLength()
                && password.length() <= AuthConfig.getPasswordMaxLength();
    }
}

src/main/webapp/health_service/index.xhtml
<ui:composition
        template="#{stdTemplate.masterLayout}"
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
>
    <ui:define name="title">#{i18n["health.service.signIn"]}</ui:define>

    <ui:define name="js">
        <h:outputScript library="_default"
                        name="js/hs_signin.js"
                        target="body"/>
    </ui:define>

    <ui:define name="sidebar"/>

    <ui:define name="header"/>

    <ui:define name="content">
        <div id="sign-in-i18n" data-i18n="{
            &quot;hs&quot;: {
                &quot;empty&quot;: &quot;#{i18n['health.service.signIn.hs.empty']}&quot;
            },
            &quot;password&quot;: {
                &quot;empty&quot;: &quot;#{i18n['signin.password.required']}&quot;,
                &quot;minLength&quot;: &quot;#{i18n['signin.password.minLength']}&quot;,
                &quot;maxLength&quot;: &quot;#{i18n['signin.password.maxLength']}&quot;
            }
        }"></div>

        <div class="sign-in-fixed">
            <div class="sign-in">
                <div class="content">
                    <h:link outcome="/index"
                            styleClass="sign-in-return logo medium"
                            p:data-inverted=""
                            p:data-tooltip="#{i18n['signin.return']}"
                            p:data-position="top center">
                    </h:link>
                    <div class="ui piled segment">
                        <form id="sign-in-form"
                              class="ui attached form segment large"
                        >
                            <h1 class="ui horizontal divider header">
                                <i class="shield icon"/>
                            </h1>
                            <div class="field">
                                <label>#{i18n['common.healthService']}</label>
                                <input type="hidden" id="sign-in-hs-id" name="health_service"/>
                                <div id="sign-in-dropdown"
                                     class="ui floating dropdown labeled icon button fluid large">
                                    <i class="dot circle outline icon"/>
                                    <span class="text full-width">#{i18n["health.service.choose"]}</span>
                                    <div class="menu">
                                        <div class="header">
                                            #{i18n["health.service.search"]}
                                        </div>
                                        <div class="ui icon search input">
                                            <i class="search icon"/>
                                            <input type="text" placeholder="#{i18n['common.search']}..."/>
                                        </div>
                                        <div class="divider"></div>
                                        <div class="header">
                                            <i class="filter icon"/>
                                            #{i18n["health.service.filter"]}
                                        </div>
                                        <div class="scrolling menu" id="crest-container">
                                            <ui:repeat value="#{healthService.healthServices}" var="hs">
                                                <div class="item" data-value="#{hs.id}">
                                                    <h:graphicImage library="_default"
                                                                    name="#{hs.crestAsResource}"
                                                                    alt="Avatar"
                                                                    style="width: 2em; height: auto; vertical-align: middle"
                                                                    styleClass="ui image bordered rounded middle aligned"
                                                    />
                                                    #{hs.province.nameLongCapitalized}
                                                    <span class="text-light text-right">#{hs.id}</span>
                                                </div>
                                            </ui:repeat>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field">
                                <label>#{i18n['common.password']}</label>
                                <div class="ui left icon input">
                                    <input
                                            id="sign-in-password"
                                            type="password"
                                            name="password"
                                            placeholder="#{i18n['common.password']}"
                                            required=""
                                            autocomplete="off"
                                            spellcheck="false"
                                            minlength="#{auth.passwordMinLength}"
                                            maxlength="#{auth.passwordMaxLength}"
                                    />
                                    <i class="lock icon"/>
                                </div>
                            </div>
                            <div class="field">
                                <div class="ui checkbox" id="sign-in-remember">
                                    <input type="checkbox"
                                           name="remember"
                                           class="hidden"
                                           tabindex="0"/>
                                    <label>#{i18n["signin.remember"]}</label>
                                </div>
                            </div>

                            <div class="ui blue fluid big button submit" tabindex="0">
                                <i class="send icon"/>
                                #{i18n['common.signIn']}
                            </div>

                            <div class="ui error message"></div>

                            <div class="ui icon warning message medium">
                                <i class="exclamation triangle icon"/>
                                <div class="content">
                                    <div class="header">
                                        #{i18n["health.service.signIn.error.message"]}
                                    </div>
                                    <p>
                                        #{i18n["health.service.signIn.error.subMessage"]}
                                        <br/>
                                        #{i18n["common.errorCode"]}: <span id="sign-in-error-code"/>
                                    </p>
                                </div>
                            </div>

                            <div class="ui icon success message medium">
                                <i class="checkmark icon"/>
                                <div class="content">
                                    <div class="header">
                                        #{i18n["health.service.signIn.success.message"]}
                                    </div>
                                    <p>#{i18n["health.service.signIn.success.subMessage"]}</p>
                                </div>
                            </div>
                        </form>

                        <div class="ui large bottom attached message">
                            <i class="info circle icon"/>
                            <span>#{i18n["signin.message"]}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </ui:define>

    <ui:define name="footer"/>
</ui:composition>