src/main/java/it/unitn/disi/wp/cup/bean/dao/HealthServiceDaoBean.java
package it.unitn.disi.wp.cup.bean.dao;

import it.unitn.disi.wp.cup.persistence.dao.HealthServiceDAO;
import it.unitn.disi.wp.cup.persistence.dao.PersonDAO;
import it.unitn.disi.wp.cup.persistence.dao.PrescriptionExamDAO;
import it.unitn.disi.wp.cup.persistence.dao.PrescriptionMedicineDAO;
import it.unitn.disi.wp.cup.persistence.dao.exception.DAOException;
import it.unitn.disi.wp.cup.persistence.dao.exception.DAOFactoryException;
import it.unitn.disi.wp.cup.persistence.dao.factory.DAOFactory;
import it.unitn.disi.wp.cup.persistence.entity.HealthService;
import it.unitn.disi.wp.cup.persistence.entity.Province;
import it.unitn.disi.wp.cup.persistence.entity.Person;
import it.unitn.disi.wp.cup.persistence.entity.PrescriptionExam;
import it.unitn.disi.wp.cup.persistence.entity.PrescriptionMedicine;
import it.unitn.disi.wp.cup.util.AuthUtil;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import java.io.Serializable;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * {@link HealthService Health Service} Bean
 *
 * @author Carlo Corradini
 * @see HealthService
 */
@Named("healthService")
@RequestScoped
public final class HealthServiceDaoBean implements Serializable {
    private static final long serialVersionUID = 9217930324705051203L;
    private static final Logger LOGGER = Logger.getLogger(HealthServiceDaoBean.class.getName());

    private PrescriptionExamDAO prescriptionExamDAO = null;
    private PrescriptionMedicineDAO prescriptionMedicineDAO = null;
    private HealthServiceDAO healthServiceDAO = null;
    private HealthService authHealthService = null;
    private PersonDAO personDAO = null;

    /**
     * Initialize the {@link HealthServiceDaoBean}
     */
    @PostConstruct
    public void init() {
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();

        if (context.getRequest() instanceof HttpServletRequest) {
            authHealthService = AuthUtil.getAuthHealthService((HttpServletRequest) context.getRequest());
            try {
                healthServiceDAO = DAOFactory.getDAOFactory().getDAO(HealthServiceDAO.class);
                prescriptionExamDAO = DAOFactory.getDAOFactory().getDAO(PrescriptionExamDAO.class);
                prescriptionMedicineDAO = DAOFactory.getDAOFactory().getDAO(PrescriptionMedicineDAO.class);
                personDAO = DAOFactory.getDAOFactory().getDAO(PersonDAO.class);
            } catch (DAOFactoryException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get DAOs", ex);
            }
        }
    }

    /**
     * Return the authenticated Health Service in the current session
     *
     * @return The authenticated Health Service in the current session, null otherwise
     */
    public HealthService getAuthHealthService() {
        return authHealthService;
    }

    /**
     * Return the {@link List} of {@link Person Patients} that live in the same {@link Province Province}
     * managed by the current authenticated {@link HealthService Health Service}
     *
     * @return The {@link List} of all {@link Person Patients}
     */
    public List<Person> getPatients() {
        List<Person> patients = Collections.emptyList();

        if (authHealthService != null && personDAO != null) {
            try {
                patients = personDAO.getAllByHealthServiceId(authHealthService.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get the List of All Patients for the authenticated Health Service", ex);
            }
        }

        return patients;
    }

    /**
     * Return the {@link List list} of all {@link HealthService Health Services} available
     *
     * @return The {@link List list} of all {@link HealthService Health Services} available
     */
    public List<HealthService> getHealthServices() {
        List<HealthService> healthServices = Collections.emptyList();

        if (healthServiceDAO != null) {
            try {
                healthServices = healthServiceDAO.getAll();
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get the List of Health Services", ex);
            }
        }

        return healthServices;
    }

    /**
     * Return the {@link List list} of all assigned {@link PrescriptionExam Prescription Exam}
     * to the Authenticated {@link HealthService Health Service}
     *
     * @return The {@link List list} of all assigned {@link PrescriptionExam}
     */
    public List<PrescriptionExam> getAssignedPrescriptionExam() {
        List<PrescriptionExam> exams = Collections.emptyList();

        if (authHealthService != null && prescriptionExamDAO != null) {
            try {
                exams = prescriptionExamDAO.getAllByHealthServiceId(authHealthService.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get the List of All Assigned Prescription Exam for authenticated Health Service", ex);
            }
        }

        return exams;
    }

    /**
     * Return the {@link List list} of all assigned but not performed {@link PrescriptionExam Prescription Exam}
     * for the Authenticated {@link HealthService Health Service}
     *
     * @return The {@link List list} of all assigned but never performed {@link PrescriptionExam Prescription Exam}
     */
    public List<PrescriptionExam> getAssignedToDoPrescriptionExam() {
        List<PrescriptionExam> exams = Collections.emptyList();

        if (authHealthService != null && prescriptionExamDAO != null) {
            try {
                exams = prescriptionExamDAO.getAllToDoByHealthServiceId(authHealthService.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get the List of All Assigned but not performed Prescription Exam for the authenticated Health Service", ex);
            }
        }

        return exams;
    }

    /**
     * Return the {@link List List} of all assigned done {@link PrescriptionExam Prescription Exam}
     * for the authenticated {@link HealthService Health Service}
     *
     * @return The {@link List list} of all assigned done {@link PrescriptionExam Prescription Exam}
     */
    public List<PrescriptionExam> getAssignedDonePrescriptionExam() {
        List<PrescriptionExam> exams = Collections.emptyList();

        if (authHealthService != null && prescriptionExamDAO != null) {
            try {
                exams = prescriptionExamDAO.getAllDoneByHealthServiceId(authHealthService.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get the List of All Assigned done Prescription Exam for the Authenticated Health Service", ex);
            }
        }

        return exams;
    }

    /**
     * Return the {@link List List} of all NOT assigned/scheduled {@link PrescriptionExam Prescription Exam}
     * for the current Authenticated Health Service
     *
     * @return The {@link List List} of all NOT assigned {@link PrescriptionExam Prescription Exam}
     */
    public List<PrescriptionExam> getNotAssignedPrescriptionExam() {
        List<PrescriptionExam> exams = Collections.emptyList();

        if (authHealthService != null && prescriptionExamDAO != null) {
            try {
                exams = prescriptionExamDAO.getAllToAssignByHealthServiceId(authHealthService.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get the List of All Not Assigned Prescription Exam for the Authenticated Health Service", ex);
            }
        }

        return exams;
    }

    /**
     * Return the {@link List List} of all NOT assigned/scheduled {@link PrescriptionMedicine Prescription Medicine}
     * for the current Authenticated Health Service
     *
     * @return The {@link List List} of all NOT assigned {@link PrescriptionMedicine Prescription Medicine}
     */
    public List<PrescriptionMedicine> getNotAssignedPrescriptionMedicine() {
        List<PrescriptionMedicine> medicines = Collections.emptyList();

        if (authHealthService != null && prescriptionMedicineDAO != null) {
            try {
                medicines = prescriptionMedicineDAO.getAllToAssignByHealthServiceId(authHealthService.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get the List of All Not Assigned Prescription Medicine for the Authenticated Health Service", ex);
            }
        }

        return medicines;
    }

    /**
     * Return the Number of {@link PrescriptionExam exams} assigned but NOT performed to the Authenticated {@link HealthService Health Service}
     *
     * @return Number of assigned but NOT performed {@link PrescriptionExam exams}
     */
    public Long getAssignedToDoPrescriptionExamCount() {
        long count = 0L;

        if (authHealthService != null && prescriptionExamDAO != null) {
            try {
                count = prescriptionExamDAO.getCountToDoByHealthServiceId(authHealthService.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to count the assigned and not performed Prescription Exam for the authenticated Health Service", ex);
            }
        }

        return count;
    }

    /**
     * Return the Number of {@link PrescriptionExam Prescription Exams} assigned and performed to the Authenticated {@link HealthService Health Service}
     *
     * @return Number of assigned and performed {@link PrescriptionExam Prescription Exams}
     */
    public Long getAssignedDonePrescriptionExamCount() {
        long count = 0L;

src/main/java/it/unitn/disi/wp/cup/persistence/entity/Person.java
package it.unitn.disi.wp.cup.persistence.entity;

import it.unitn.disi.wp.cup.util.StringUtil;

import java.time.LocalDate;
import java.util.List;

/**
 * Entity Person
 *
 * @author Carlo Corradini
 */
public class Person {

    private Long id;
    private String email;
    private String password;
    private String name;
    private String surname;
    private PersonSex sex;
    private String fiscalCode;
    private LocalDate birthDate;
    private City birthCity;
    private City city;
    private PersonAvatar avatar;
    private List<PersonAvatar> avatarHistory;
    private List<PrescriptionExam> exams;
    private List<PrescriptionMedicine> medicines;

    @Override
    public boolean equals(Object obj) {
        Person person;
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        person = (Person) obj;
        return id.equals(person.id);
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        return prime + ((id == null) ? 0 : id.hashCode());
    }

    /**
     * Return the id of the Person
     *
     * @return Person id
     */
    public Long getId() {
        return id;
    }

    /**
     * Set the Person id
     *
     * @param id Person id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Return the email of the Person
     *
     * @return Person email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Set the Person email
     *
     * @param email Person email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Return the password of the Person
     *
     * @return Person password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the Person password
     *
     * @param password Person password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Return the name of the Person
     *
     * @return Person name
     */
    public String getName() {
        return name;
    }

    /**
     * Return the name of the Person capitalized
     *
     * @return Person name capitalized
     */
    public String getNameCapitalized() {
        return StringUtil.capitalize(name);
    }

    /**
     * Set the name of the Person
     *
     * @param name Person name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Return the surname of the Person
     *
     * @return Person surname
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Return the surname of the Person capitalized
     *
     * @return Person surname capitalized
     */
    public String getSurnameCapitalized() {
        return StringUtil.capitalize(surname);
    }

    /**
     * Set the surname of the Person
     *
     * @param surname Person surname
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * Return the Full Name of the Person
     *
     * @return Full Name of the Person
     */
    public String getFullName() {
        return getName() + " " + getSurname();
    }

    /**
     * Return the Full Name of the Person Capitalized
     *
     * @return Capitalized Full Name of the Person
     */
    public String getFullNameCapitalized() {
        return getNameCapitalized() + " " + getSurnameCapitalized();
    }

    /**
     * Return the sex of the Person
     *
     * @return Person sex
     */
    public PersonSex getSex() {
        return sex;
    }

    /**
     * Set the sex of the Person
     *
     * @param sex Person sex
     */
    public void setSex(PersonSex sex) {
        this.sex = sex;
    }

    /**
     * Return the fiscal code of the Person
     *
     * @return Person fiscal code
     */
    public String getFiscalCode() {
        return fiscalCode;
    }

    /**
     * Set the fiscal code of the Person
     *
     * @param fiscalCode Person fiscal code
     */
    public void setFiscalCode(String fiscalCode) {
        this.fiscalCode = fiscalCode;
    }

    /**
     * Return the birth date of the Person
     *
     * @return Person birth date
     */
    public LocalDate getBirthDate() {
        return birthDate;
    }

    /**
     * Set the birth date of the Person
     *
     * @param birthDate Person birth date
     */
    public void setBirthDate(LocalDate birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * Return the birth city of the Person
     *
     * @return Person birth city
     */
    public City getBirthCity() {
        return birthCity;
    }

    /**
     * Set the birth city of the Person
     *
     * @param birthCity Person birth city
     */
    public void setBirthCity(City birthCity) {
        this.birthCity = birthCity;
    }

    /**
     * Return the city of the Person
     *
     * @return Person city
     */
    public City getCity() {
        return city;
    }

    /**
     * Set the city of the Person
     *
     * @param city Person city
     */
    public void setCity(City city) {
        this.city = city;
    }

    /**
     * Return the avatar of the Person
     *
     * @return Person avatar
     */
    public PersonAvatar getAvatar() {
        return avatar;
    }

    /**
     * Set the avatar of the Person
     *
     * @param avatar Person avatar
     */
    public void setAvatar(PersonAvatar avatar) {
        this.avatar = avatar;
    }

    /**
     * Return the avatar history of the Person
     *
     * @return Person avatar history
     */
    public List<PersonAvatar> getAvatarHistory() {
        return avatarHistory;
    }

    /**
     * Set the avatar history of the Person
     *
     * @param avatarHistory Person avatar history
     */
    public void setAvatarHistory(List<PersonAvatar> avatarHistory) {
        this.avatarHistory = avatarHistory;
    }

    /**
     * Return the exams of the Person
     *
     * @return Person exams
     */
    public List<PrescriptionExam> getExams() {
        return exams;
    }

    /**
     * Set the exams of the Person
     *
     * @param exams Person exams
     */
    public void setExams(List<PrescriptionExam> exams) {
        this.exams = exams;
    }

    /**
     * Return the medicines of the Person
     *
     * @return Person medicines
     */
    public List<PrescriptionMedicine> getMedicines() {
        return medicines;
    }

    /**
     * Set the medicines of the Person
     *
     * @param medicines Person medicines
     */
    public void setMedicines(List<PrescriptionMedicine> medicines) {
        this.medicines = medicines;
    }
}

src/main/webapp/dashboard/specialist/index.xhtml
<ui:composition
        template="#{stdTemplate.masterLayout}"
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:fn="http://java.sun.com/jsp/jstl/functions"
>
    <ui:define name="title">#{i18n["common.dashboard.specialist"]}</ui:define>

    <ui:define name="js">
        <h:outputScript library="datatables"
                        name="js/datatables.min.js"
                        target="body"/>
        <h:outputScript library="_default"
                        name="js/dashboard_doctor_specialist.js"
                        target="body"/>
    </ui:define>

    <ui:define name="content">
        <ui:fragment rendered="#{not empty doctorSpecialist.authDoctorSpecialist}">

            <h2 class="ui center aligned icon header">
                <i class="street view icon"/>
                #{person.authPerson.fullNameCapitalized}
                <br/>
                <span class="text-smaller-33 text-light">
                <h:outputText value="#{doctorSpecialist.authDoctorSpecialist.since}">
                    <f:convertDateTime type="localDate"/>
                </h:outputText>
                </span>
            </h2>

            <div class="ui divider"></div>

            <div class="ui two statistics">
                <div class="statistic">
                    <div class="label">
                        #{i18n["common.todoVisits"]}
                    </div>
                    <div class="value">
                        #{doctorSpecialist.assignedToDoPrescriptionExamCount}
                    </div>
                </div>
                <div class="statistic">
                    <div class="label">
                        #{i18n["common.total.assignedVisits"]}
                    </div>
                    <div class="value">
                        #{doctorSpecialist.assignedDonePrescriptionExamCount}
                    </div>
                </div>
            </div>

            <div class="ui divider"></div>

            <div class="ui top attached tabular menu" id="dashboard-doctor-specialist-tab">
                <a class="item active" data-tab="qualification">
                    <i class="certificate icon"/>
                    <span>#{i18n["common.qualifications"]}</span>
                </a>
                <a class="item" data-tab="services">
                    <i class="compass outline icon"/>
                    <span>#{i18n["common.services"]}</span>
                </a>
            </div>

            <div class="ui bottom attached tab segment active" data-tab="qualification">
                <ui:fragment rendered="#{empty doctorSpecialist.qualifiedExams}">
                    <div class="ui icon floating message">
                        <i class="info circle icon"/>
                        <div class="content">
                            <div class="header">
                                #{i18n["dashboard.specialist.qualifiedExam.empty.message"]}
                            </div>
                            <p>#{i18n["dashboard.specialist.qualifiedExam.empty.subMessage"]}</p>
                        </div>
                    </div>
                </ui:fragment>
                <ui:fragment rendered="#{not empty doctorSpecialist.qualifiedExams}">
                    <table class="ui celled striped sortable table"
                           id="dashboard-doctor-specialist-qualification-table">
                        <thead>
                        <tr>
                            <th>#{i18n["common.id"]}</th>
                            <th>#{i18n["common.name"]}</th>
                        </tr>
                        </thead>
                        <tbody>
                        <ui:repeat value="#{doctorSpecialist.qualifiedExams}" var="qe">
                            <tr>
                                <td>#{qe.id}</td>
                                <td>#{qe.name}</td>
                            </tr>
                        </ui:repeat>
                        </tbody>
                    </table>
                </ui:fragment>
            </div>

            <div class="ui bottom attached tab segment" data-tab="services">
                <div class="ui centered cards">
                    <h:link outcome="/dashboard/specialist/patients/index" styleClass="raised link card">
                        <div class="image">
                            <h:graphicImage styleClass="ui image"
                                            library="_default"
                                            name="/images/category/group.svg"
                                            alt="#{i18n['common.patients']}"
                            />
                        </div>
                        <div class="extra center aligned">
                            #{fn:toUpperCase(i18n["common.patients"])}
                        </div>
                    </h:link>
                    <h:link outcome="/dashboard/specialist/visit_todo/index" styleClass="raised link card">
                        <div class="image">
                            <h:graphicImage styleClass="ui image"
                                            library="_default"
                                            name="/images/category/visit.svg"
                                            alt="#{i18n['common.assignedVisits']}"
                            />
                        </div>
                        <div class="extra center aligned">
                            #{fn:toUpperCase(i18n["common.todoVisits"])}
                        </div>
                    </h:link>
                    <h:link outcome="/dashboard/specialist/visit_done/index" styleClass="raised link card">
                        <div class="image">
                            <h:graphicImage styleClass="ui image"
                                            library="_default"
                                            name="/images/category/visit_check.svg"
                                            alt="#{i18n['common.total.assignedVisits']}"
                            />
                        </div>
                        <div class="extra center aligned">
                            #{fn:toUpperCase(i18n["common.total.assignedVisits"])}
                        </div>
                    </h:link>
                </div>
            </div>

            <div class="ui divider"></div>
        </ui:fragment>
    </ui:define>
</ui:composition>