src/main/java/it/unitn/disi/wp/cup/bean/config/AppConfigBean.java
package it.unitn.disi.wp.cup.bean.config;

import it.unitn.disi.wp.cup.config.AppConfig;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;

/**
 * Permits the access to web pages of the App Configuration
 *
 * @author Carlo Corradini
 * @see AppConfig
 */
@Named("app")
@ApplicationScoped
public final class AppConfigBean implements Serializable {
    private static final long serialVersionUID = 7987302702812972518L;

    /**
     * @see AppConfig#getName()
     */
    public String getName() {
        return AppConfig.getName();
    }

    /**
     * @see AppConfig#getDomain()
     */
    public String getDomain() {
        return AppConfig.getDomain();
    }

    /**
     * @see AppConfig#getHostname()
     */
    public String getHostname() {
        return AppConfig.getHostname();
    }

    /**
     * @see AppConfig#getAuthorName()
     */
    public String getAuthorName() {
        return AppConfig.getAuthorName();
    }

    /**
     * @see AppConfig#getAuthorList()
     */
    public List<String> getAuthorList() {
        return AppConfig.getAuthorList();
    }

    /**
     * @see AppConfig#getColor()
     */
    public String getColor() {
        return AppConfig.getColor();
    }

    /**
     * @see AppConfig#getSinceDay()
     */
    public static int getSinceDay() {
        return AppConfig.getSinceDay();
    }

    /**
     * @see AppConfig#getSinceMonth()
     */
    public static int getSinceMonth() {
        return AppConfig.getSinceMonth();
    }

    /**
     * @see AppConfig#getSinceYear()
     */
    public int getSinceYear() {
        return AppConfig.getSinceYear();
    }

    /**
     * @see AppConfig#getInfoEmail()
     */
    public String getInfoEmail() {
        return AppConfig.getInfoEmail();
    }

    /**
     * @see AppConfig#getInfoPhone()
     */
    public String getInfoPhone() {
        return AppConfig.getInfoPhone();
    }

    /**
     * @see AppConfig#getInfoPlaceAddress()
     */
    public String getInfoPlaceAddress() {
        return AppConfig.getInfoPlaceAddress();
    }

    /**
     * @see AppConfig#getInfoPlaceNumber()
     */
    public String getInfoPlaceNumber() {
        return AppConfig.getInfoPlaceNumber();
    }

    /**
     * @see AppConfig#getInfoPlaceCap()
     */
    public String getInfoPlaceCap() {
        return AppConfig.getInfoPlaceCap();
    }

    /**
     * @see AppConfig#getInfoPlaceCity()
     */
    public String getInfoPlaceCity() {
        return AppConfig.getInfoPlaceCity();
    }

    /**
     * @see AppConfig#getConfigAvatarMaxFileSize()
     */
    public int getConfigAvatarMaxFileSize() {
        return AppConfig.getConfigAvatarMaxFileSize();
    }
}

src/main/java/it/unitn/disi/wp/cup/bean/dao/PersonDaoBean.java
package it.unitn.disi.wp.cup.bean.dao;

import it.unitn.disi.wp.cup.persistence.dao.*;
import it.unitn.disi.wp.cup.persistence.dao.exception.DAOException;
import it.unitn.disi.wp.cup.persistence.dao.exception.DAOFactoryException;
import it.unitn.disi.wp.cup.persistence.dao.factory.DAOFactory;
import it.unitn.disi.wp.cup.persistence.entity.*;
import it.unitn.disi.wp.cup.util.AuthUtil;
import it.unitn.disi.wp.cup.util.PersonAvatarUtil;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Person Bean
 *
 * @author Carlo Corradini
 * @see Person
 */
@Named("person")
@RequestScoped
public final class PersonDaoBean implements Serializable {
    private static final long serialVersionUID = -4058980644509062209L;
    private static final Logger LOGGER = Logger.getLogger(PersonDaoBean.class.getName());

    private PersonDAO personDAO = null;
    private DoctorDAO doctorDAO = null;
    private PersonAvatarDAO personAvatarDAO = null;
    private PrescriptionMedicineDAO prescriptionMedicineDAO = null;
    private PrescriptionExamDAO prescriptionExamDAO = null;
    private Person authPerson = null;

    /**
     * Initialize the {@link PersonDaoBean}
     */
    @PostConstruct
    public void init() {
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();

        if (context.getRequest() instanceof HttpServletRequest) {
            authPerson = AuthUtil.getAuthPerson((HttpServletRequest) context.getRequest());
            try {
                personDAO = DAOFactory.getDAOFactory().getDAO(PersonDAO.class);
                doctorDAO = DAOFactory.getDAOFactory().getDAO(DoctorDAO.class);
                personAvatarDAO = DAOFactory.getDAOFactory().getDAO(PersonAvatarDAO.class);
                prescriptionMedicineDAO = DAOFactory.getDAOFactory().getDAO(PrescriptionMedicineDAO.class);
                prescriptionExamDAO = DAOFactory.getDAOFactory().getDAO(PrescriptionExamDAO.class);
            } catch (DAOFactoryException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get DAOs", ex);
            }
        }
    }

    /**
     * Return the Authenticated person in the current session
     *
     * @return The Authenticated person in the current session, null otherwise
     */
    public Person getAuthPerson() {
        return authPerson;
    }

    /**
     * Return the {@link PersonAvatar avatar} of the Authenticated {@link Person person}
     *
     * @return The {@link PersonAvatar avatar} of the {@link Person person}
     */
    public PersonAvatar getAvatar() {
        PersonAvatar avatar = null;

        if (authPerson != null && personAvatarDAO != null) {
            try {
                avatar = PersonAvatarUtil.checkPersonAvatar(personAvatarDAO.getCurrentByPersonId(authPerson.getId()),
                        authPerson.getId(),
                        authPerson.getSex());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get the current Person Avatar for the authenticated Person", ex);
            }
        }

        return avatar;
    }

    /**
     * Return the doctor as a {@link Person person} for the Authenticated Person
     *
     * @return The doctor of the {@link Person person}
     */
    public Person getDoctor() {
        Person doctor = null;
        Doctor _doctor;

        if (authPerson != null && doctorDAO != null) {
            try {
                if ((_doctor = doctorDAO.getDoctorByPatientId(authPerson.getId())) != null) {
                    // Person has a Doctor
                    doctor = personDAO.getByPrimaryKey(_doctor.getId());
                }
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get the current Doctor for the Authenticated Person", ex);
            }
        }

        return doctor;
    }

    /**
     * Return a {@link List list} of {@link Doctor doctors} represented as {@link Person persons} filtered
     * by the living {@link Province province} and {@link Doctor doctor's} history of the Authenticated {@link Person person}
     *
     * @return A {@link List list} of available {@link Doctor doctors} with the same {@link Province province}
     * and not in the {@link Doctor doctor's} history of the Authenticated {@link Person person}
     */
    public List<Person> getDoctors() {
        List<Person> doctors = Collections.emptyList();

        if (authPerson != null) {
            try {
                doctors = doctorDAO.getAllAvailableByPatientId(authPerson.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get the List of Doctors filtered by Province id and history");
            }
        }

        return doctors;
    }

    /**
     * Return the {@link LocalDateTime date} since the Authenticated {@link Person person} is a patient of the current {@link Doctor doctor}
     * If the {@link Person person} hasn't a {@link Doctor doctor} null will be returned
     *
     * @return The {@link LocalDateTime date} since the Authenticated {@link Person person} is a patient
     */
    public LocalDateTime getDoctorSince() {
        LocalDateTime since = null;

        if (authPerson != null) {
            try {
                since = doctorDAO.getSinceByPatientId(authPerson.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get Since for the authenticated Person");
            }
        }

        return since;
    }

    /**
     * Return the {@link List list} of all {@link PersonAvatar avatars} that the {@link Person person} used
     *
     * @return The {@link List list} of {@link PersonAvatar avatars}
     */
    public List<PersonAvatar> getAvatarHistory() {
        List<PersonAvatar> history = Collections.emptyList();

        if (authPerson != null && personAvatarDAO != null) {
            try {
                history = personAvatarDAO.getAllByPersonId(authPerson.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get the List of Avatar History fot the authenticated Person");
            }
        }

        return history;
    }

    /**
     * Return the {@link List list} of all {@link PrescriptionMedicine prescribed} {@link Medicine medicines} for the authenticated {@link Person person}
     *
     * @return The {@link List list} of prescribed {@link Medicine medicines}
     */
    public List<PrescriptionMedicine> getPrescribedMedicines() {
        List<PrescriptionMedicine> medicines = Collections.emptyList();

        if (authPerson != null && prescriptionMedicineDAO != null) {
            try {
                medicines = prescriptionMedicineDAO.getAllByPersonId(authPerson.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get the List of Prescribed Medicines for the authenticated Person");
            }
        }

        return medicines;
    }

    /**
     * Return the {@link List list} of all {@link PrescriptionExam prescribed} {@link Exam exams} for the authenticated {@link Person person}
     *
     * @return The {@link List list} of prescribed {@link Exam exams}
     */
    public List<PrescriptionExam> getPrescribedExams() {
        List<PrescriptionExam> exams = Collections.emptyList();

        if (authPerson != null && prescriptionExamDAO != null) {
            try {
                exams = prescriptionExamDAO.getAllByPersonId(authPerson.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to get the List of Prescribed Exams for the authenticated Person");
            }
        }

        return exams;
    }

    /**
     * Return the Number of {@link Medicine medicines} prescribed for the Authenticated {@link Person person}
     *
     * @return Number of {@link Medicine medicines} prescribed
     */
    public long getPrescriptionMedicineCount() {
        long count = 0L;

        if (authPerson != null && prescriptionMedicineDAO != null) {
            try {
                count = prescriptionMedicineDAO.getCountByPersonId(authPerson.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to count the Prescription Medicine", ex);
            }
        }

        return count;
    }

    /**
     * Return the Number of {@link Exam exams} prescribed for the Authenticated {@link Person person}
     *
     * @return Number of {@link Exam exams} prescribed
     */
    public Long getPrescriptionExamCount() {
        long count = 0L;

        if (authPerson != null && prescriptionExamDAO != null) {
            try {
                count = prescriptionExamDAO.getCountByPersonId(authPerson.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to count the Prescription Exam", ex);
            }
        }

        return count;
    }

    /**
     * Return the Number of {@link PrescriptionExam exams} with {@link Report report} prescribed
     * for the Authenticated {@link Person person} that has not been read
     *
     * @return Number of {@link Exam exams} with {@link Report report} that has not been read
     */
    public Long getPrescriptionExamNotReadCount() {
        long count = 0L;

        if (authPerson != null && prescriptionExamDAO != null) {
            try {
                count = prescriptionExamDAO.getCountNotReadByPersonId(authPerson.getId());
            } catch (DAOException ex) {
                LOGGER.log(Level.SEVERE, "Unable to count the Prescription Exam that has not been read", ex);

src/main/java/it/unitn/disi/wp/cup/persistence/entity/Province.java
package it.unitn.disi.wp.cup.persistence.entity;

import it.unitn.disi.wp.cup.util.StringUtil;

/**
 * Entity Province
 *
 * @author Carlo Corradini
 */
public class Province {
    private Long id;
    private String nameLong;
    private String nameShort;
    private Region region;

    @Override
    public boolean equals(Object obj) {
        Province province;
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        province = (Province) obj;
        return id.equals(province.id);
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        return prime + ((id == null) ? 0 : id.hashCode());
    }

    /**
     * Return the id of the Province
     *
     * @return Province id
     */
    public Long getId() {
        return id;
    }

    /**
     * Set the Province id
     *
     * @param id Province id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Return the name long of the Province
     *
     * @return Province name long
     */
    public String getNameLong() {
        return nameLong;
    }

    /**
     * Return the name long of the Province capitalized
     *
     * @return Province name long capitalized
     */
    public String getNameLongCapitalized() {
        return StringUtil.capitalize(nameLong);
    }

    /**
     * Set the Province name long
     *
     * @param nameLong Province name long
     */
    public void setNameLong(String nameLong) {
        this.nameLong = nameLong;
    }

    /**
     * Return the name short of the Province
     * The name short is always in Upper Case
     *
     * @return Province name short
     */
    public String getNameShort() {
        return nameShort.toUpperCase();
    }

    /**
     * Set the Province name short
     *
     * @param nameShort Province name short
     */
    public void setNameShort(String nameShort) {
        this.nameShort = nameShort;
    }

    /**
     * Return the Region of the Province
     *
     * @return Province Region
     */
    public Region getRegion() {
        return region;
    }

    /**
     * Set the Province region
     *
     * @param region Province region
     */
    public void setRegion(Region region) {
        this.region = region;
    }
}

src/main/webapp/WEB-INF/templates/standard/partials/content.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
>
    <div class="ui info message">
        <div class="header">
            Default Content
        </div>
        <p><i class="blind icon"/></p>
    </div>
</ui:composition>

src/main/webapp/WEB-INF/templates/standard/partials/footer.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:fn="http://java.sun.com/jsp/jstl/functions"
        xmlns:h="http://java.sun.com/jsf/html"
>
    <footer class="footer">
        <div class="footer-limiter">
            <div class="footer-center">
                <div class="element">
                    <i class="map marker alternate icon"/>
                    <p>
                        <span class="address">
                            #{app.infoPlaceAddress} #{app.infoPlaceNumber}
                        </span>
                        #{app.infoPlaceCity}, #{app.infoPlaceCap}
                    </p>
                    <div class="ui divider"></div>
                </div>
                <div class="element">
                    <i class="phone icon"/>
                    <p>+39 #{app.infoPhone}</p>
                    <div class="ui divider"></div>
                </div>
                <div class="element">
                    <i class="envelope icon"/>
                    <p>
                        <a href="mailto:#{app.infoEmail}">
                            #{app.infoEmail}
                        </a>
                    </p>
                </div>
            </div>
            <div class="footer-right">
                <div class="legal">
                    <div class="item">
                        <h:link outcome="/privacy/index">
                            <i class="shield alternate icon fitted"/>
                            &#160;#{i18n["common.privacy"]}
                        </h:link>
                    </div>
                    <div class="item">
                        <h:link outcome="/cookie/index">
                            <i class="basketball ball icon fitted"/>
                            &#160;#{i18n["common.cookie"]}
                        </h:link>
                    </div>
                    <div class="ui divider"></div>
                    <div class="item">
                        <h:link outcome="/health_service/index">
                            <i class="h square icon fitted"/>
                            &#160;#{i18n["common.healthService"]}
                        </h:link>
                    </div>
                </div>
                <div class="made-with-love">
                    Made with <i class="heart icon fitted"/> in
                    <span>It</span><span>a</span><span>ly</span>
                </div>
            </div>
            <div class="footer-left">
                <div class="logo"></div>
                <div class="credits">
                    #{fn:toUpperCase(app.name)} <span>by #{app.authorName}</span>
                </div>
                <div class="copyright">
                    #{fn:toUpperCase(app.name)}&#160;
                    <i class="copyright outline icon fitted"/>
                    &#160;#{app.sinceYear} - #{calendar.year}
                </div>
            </div>
        </div>
    </footer>
</ui:composition>

src/main/webapp/WEB-INF/templates/standard/partials/sidebar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:fn="http://java.sun.com/jsp/jstl/functions"
                xmlns:ui="http://java.sun.com/jsf/facelets"
>
    <ui:fragment rendered="#{not empty person.authPerson or not empty healthService.authHealthService}">
        <nav class="ui left sidebar vertical menu big" id="sidebar-menu">

            <div class="close-container">
                <div id="sidebar-menu-close" class="close"></div>
            </div>

            <!-- HEALTH SERVICE-->
            <ui:fragment rendered="#{not empty healthService.authHealthService}">
                <div class="avatar">
                    <div class="avatar-preview crest">
                        <h:graphicImage library="_default"
                                        name="#{healthService.authHealthService.crestAsResource}"
                                        alt="Crest"
                        />
                    </div>
                </div>

                <h4 class="name-surname text-overflow-ellipsis">
                    #{healthService.authHealthService.province.nameLongCapitalized}
                </h4>

                <div class="item">
                    <div class="ui input disabled">
                        <input type="text" placeholder="#{i18n['common.search']}..."/>
                    </div>
                </div>

                <h:link outcome="/health_service/dashboard/index"
                        styleClass="item"
                >
                    <i class="h square icon"/>
                    #{i18n["common.dashboard"]}
                </h:link>

                <div class="item">
                    <div class="header">#{i18n["common.services"]}</div>
                    <div class="menu">
                        <h:link outcome="/health_service/dashboard/visit_assign/index"
                                styleClass="item"
                        >
                            #{i18n["common.assignVisits"]}
                            <span class="ui red label">#{healthService.notAssignedPrescriptionExamCount}</span>
                        </h:link>
                        <h:link outcome="/health_service/dashboard/visit_todo/index"
                                styleClass="item"
                        >
                            #{i18n["common.todoVisits"]}
                            <span class="ui green label">#{healthService.assignedToDoPrescriptionExamCount}</span>
                        </h:link>
                        <h:link outcome="/health_service/dashboard/visit_done/index"
                                styleClass="item"
                        >
                            #{i18n["common.total.assignedVisits"]}
                            <span class="ui yellow empty circular label"/>
                        </h:link>
                        <h:link outcome="/health_service/dashboard/medicine_assign/index"
                                styleClass="item"
                        >
                            #{i18n["common.assignMedicines"]}
                            <span class="ui teal label">#{healthService.notAssignedPrescriptionMedicineCount}</span>
                        </h:link>
                        <h:link outcome="/health_service/dashboard/report/index"
                                styleClass="item"
                        >
                            #{i18n["health.service.report"]}
                            <span class="ui blue empty circular label"/>
                        </h:link>
                        <h:link outcome="/health_service/dashboard/patients/index"
                                styleClass="item"
                        >
                            #{i18n["common.patients"]}
                            <span class="ui purple empty circular label"/>
                        </h:link>
                    </div>
                </div>
            </ui:fragment>
            <!-- END HEALTH SERVICE -->

            <!-- PERSON -->
            <ui:fragment rendered="#{not empty person.authPerson}">
                <div id="sidebar-avatar-error" class="hidden">
                    <div class="ui negative message tiny">
                        <i class="exclamation triangle icon"/>
                        #{i18n["sidebar.avatar.error"]}
                        <h:outputText value="#{app.configAvatarMaxFileSize / 1024}">
                            <f:convertNumber integerOnly="true"/>
                        </h:outputText>
                        KByte
                    </div>
                </div>

                <div class="avatar">
                    <div class="avatar-edit">
                        <input type="file" id="sidebar-avatar-input"
                               accept=".png, .jpg, .jpeg"
                               data-max-size="#{app.configAvatarMaxFileSize}"
                        />
                        <label for="sidebar-avatar-input">
                            <i class="pencil alternate icon"/>
                        </label>
                    </div>
                    <div class="avatar-save hidden" id="sidebar-avatar-save">
                        <i class="save outline icon blue"/>
                        <i class="check icon green hidden"/>
                        <i class="close icon red hidden"/>
                        <i class="notched circle loading icon hidden"/>
                    </div>
                    <div class="avatar-preview">
                        <h:graphicImage id="sidebar-avatar-image"
                                        styleClass="person-avatar"
                                        library="_default"
                                        name="#{person.avatar.nameAsResource}"
                                        alt="Avatar"
                        />
                    </div>
                </div>

                <h4 class="name-surname text-overflow-ellipsis">
                    #{person.authPerson.fullNameCapitalized}
                </h4>

                <div class="item">
                    <div class="ui input disabled">
                        <input type="text" placeholder="#{i18n['common.search']}..."/>
                    </div>
                </div>

                <h:link outcome="/dashboard/private/index"
                        styleClass="item"
                >
                    <i class="th icon"/>
                    #{i18n["common.dashboard.personal"]}
                </h:link>
                <h:link outcome="/dashboard/doctor/index"
                        styleClass="item"
                        rendered="#{not empty doctor.authDoctor}"
                >
                    <i class="user md icon"/>
                    #{i18n["common.dashboard.doctor"]}
                </h:link>
                <h:link outcome="/dashboard/specialist/index"
                        styleClass="item"
                        rendered="#{not empty doctorSpecialist.authDoctorSpecialist}">
                    <i class="street view icon"/>
                    #{i18n["common.dashboard.specialist"]}
                </h:link>

                <div class="item">
                    <div class="header">#{i18n["common.personal"]}</div>
                    <div class="menu">
                        <h:link outcome="/dashboard/private/report/index"
                                styleClass="item">
                            #{i18n["common.reportsNew"]}
                            <span class="ui red label">#{person.prescriptionExamNotReadCount}</span>
                        </h:link>
                        <h:link outcome="/dashboard/private/exam/index"
                                styleClass="item">
                            #{i18n["common.exams"]}
                            <span class="ui yellow empty circular label"/>
                        </h:link>
                        <h:link outcome="/dashboard/private/prescription/index"
                                styleClass="item">
                            #{i18n["common.prescriptions"]}
                            <span class="ui green empty circular label"/>
                        </h:link>
                    </div>
                </div>

                <!-- DOCTOR -->
                <ui:fragment rendered="#{not empty doctor.authDoctor}">
                    <div class="item">
                        <div class="header">#{i18n["common.doctor"]}</div>
                        <div class="menu">
                            <h:link outcome="/dashboard/doctor/patients/index"
                                    styleClass="item">
                                #{i18n["common.patients"]}
                                <span class="ui red empty circular label"/>
                            </h:link>
                            <h:link outcome="/dashboard/doctor/prescription_medicine/index"
                                    styleClass="item">
                                #{i18n["common.prescriptionMedicine"]}
                                <span class="ui yellow empty circular label"/>
                            </h:link>
                            <h:link outcome="/dashboard/doctor/prescription_exam/index"
                                    styleClass="item">
                                #{i18n["common.prescriptionExam"]}
                                <span class="ui green empty circular label"/>
                            </h:link>
                        </div>
                    </div>
                </ui:fragment>

                <!-- SPECIALIST -->
                <ui:fragment rendered="#{not empty doctorSpecialist.authDoctorSpecialist}">
                    <div class="item">
                        <div class="header">#{i18n["common.specialist"]}</div>
                        <div class="menu">
                            <h:link outcome="/dashboard/specialist/patients/index"
                                    styleClass="item"
                            >
                                #{i18n["common.patients"]}
                                <span class="ui red empty circular label"/>
                            </h:link>
                            <h:link outcome="/dashboard/specialist/visit_todo/index"
                                    styleClass="item"
                            >
                                #{i18n["common.todoVisits"]}
                                <span class="ui yellow label">#{doctorSpecialist.assignedToDoPrescriptionExamCount}</span>
                            </h:link>
                            <h:link outcome="/dashboard/specialist/visit_done/index"
                                    styleClass="item"
                            >
                                #{i18n["common.total.assignedVisits"]}
                                <span class="ui green empty circular label"/>
                            </h:link>
                        </div>
                    </div>
                </ui:fragment>
            </ui:fragment>
            <!-- END PERSON -->

            <div class="item">
                <div class="header">
                    <i class="info circular icon"/> #{fn:toUpperCase(i18n["common.help"])}
                </div>
                <div class="menu">
                    <h:link outcome="/info/exam/index"
                            styleClass="item"
                    >
                        #{i18n["info.exam"]}
                        <span class="ui red empty circular label"/>
                    </h:link>
                    <h:link outcome="/info/medicine/index"
                            styleClass="item"
                    >
                        #{i18n["info.medicine"]}
                        <span class="ui yellow empty circular label"/>
                    </h:link>
                </div>
            </div>

            <div class="item">
                <a href="#{request.contextPath}/signout.handler" class="ui red fluid button">
                    #{i18n['common.signOut']}
                </a>
            </div>
        </nav>
    </ui:fragment>
</ui:composition>